### ISSUE TITLE
restart problem

### ISSUE THREAD

**Issue by amirjr1378** [LobsterBandit/use-countdown-timer#29]
i cannot reset() then start() again because when i want to start countdown is 0 and doesnt trigger the start

**Comment by LobsterBandit** [comment]
I'm not able to reproduce: https://codesandbox.io/s/holy-dream-kjqrf?file=/src/App.js

Are you able to post an example or maybe recreate in codesandbox?

**Comment by amirjr1378** [comment]
> I'm not able to reproduce: https://codesandbox.io/s/holy-dream-kjqrf?file=/src/App.js
> 
> Are you able to post an example or maybe recreate in codesandbox?

my example
https://codesandbox.io/s/cocky-elion-6ydps?file=/src/App.js

**Comment by LobsterBandit** [comment]
Looks like the if statement [here](https://github.com/LobsterBandit/use-countdown-timer/blob/master/src/index.ts#L36) is preventing the state update in `start` when called immediately after `reset` in the same function.

I'll play with it and see if I can push a fix today.

**Comment by LobsterBandit** [comment]
Resolved in v1.3.1
