### ISSUE TITLE
interval performance issue

### ISSUE THREAD

**Issue by amirjr1378** [LobsterBandit/use-countdown-timer#44]
when i pause actually what it happens it make isRunning and canStart to false , but i don't see clear interval for this senario 
i think my solution can resolve this issue but i think i need to move interval ids in top level so i can access it on next render use Effect.
![image](https://user-images.githubusercontent.com/49060396/129223404-809250d4-c720-4a51-84e7-c71577cbf332.png)

**Comment by LobsterBandit** [comment]
The interval should be cleared even on pause. A change in those state values triggers the `useEffect` again which runs the cleanup function to clear out any existing interval, `() => clearInterval(id)`.

https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update

**Comment by amirjr1378** [comment]
a change in those state values  does not triggers the useEffect cleanup function, i think clean up function run when the component is unmounted an is no longer on the screen.

**Comment by LobsterBandit** [comment]
From https://reactjs.org/docs/hooks-effect.html#explanation-why-effects-run-on-each-update

> Explanation: Why Effects Run on Each Update
> If you’re used to classes, you might be wondering why the effect cleanup phase happens after every re-render, and not just once during unmounting.

Cleanup does happen on unmount but also every render.

**Comment by amirjr1378** [comment]
oh now i get it , i didnt think clean up happen after rerenders too.
TNX ALOT
