### ISSUE TITLE
after expire, don't reset to initial value

### ISSUE THREAD

**Issue by brumm** [LobsterBandit/use-countdown-timer#5]
Hey there, and thanks for the neat hook.

In my use case, I'm displaying a decreasing circular progress bar, based on the countdown. Currently when the countdown expires, the countdown value resets to initial, and causes my progress bar to rewind. I'd like to be able to stay at 0 value and only reset to initial when I actually call reset.

I would argue that this behavior should be the default one... what do you think?

**Comment by LobsterBandit** [comment]
That makes sense.  Maybe change this default and add some kind of automatic reset toggle so that an explicit reset call is not needed to restart an expired timer.

**Comment by janrembold** [comment]
Just opened a PR for this feature request: https://github.com/LobsterBandit/use-countdown-timer/pull/24
